const locations = [
  //vill du bidra lägg in saker här:// template:
  // {
  //   name: "Plats",
  //   roles: [
  //     "yrke",
  //     "yrke",
  //   ],
  // },

  {
    name: "Airplane",
    roles: [
      "First class passenger",
      "Mechanic",
      "Flight attendant",
      "Pilot",
      "Terrorist",
      "Regular passenger",
      "Barnet som skriker under hela flygresan",
      "co-pilot",
    ],
  },
  {
    name: "Bank",
    roles: [
      "Manager",
      "Consult",
      "Bank robber",
      "SecuritasVakt",
      "Bank assistant",
      "Customer",
      "Dog tied to a post outside",
    ],
  },
  {
    name: "Beach",
    roles: [
      "Surfer",
      "Farsan med alldeles för mycket solkräm",
      "Life guard",
      "Snubben som flexar sina muskler lite för mycket",
      "Stekheta bruden som alla kollar på",
      "Ice cream man",
      "Barn som drunknar",
    ],
  },
  {
    name: "Church",
    roles: [
      "Priest",
      "Syndare",
      "Old lady",
      "Snubbe som konfirmerar sig för pengarna",
      "Gubbe som spelar Orgel",
      "Tourist",
    ],
  },
  {
    name: "Circus",
    roles: [
      "Acrobat",
      "Lion tamer",
      "Clown",
      "Fire breather",
      "Barn som äter för mycket popcorn och dör",
      "Audience",
      "Critic",
    ],
  },
  {
    name: "After work",
    roles: [
      "CEO",
      "Snubben som inte var inbjuden",
      "Strippan som var tänkt som underhållning",
      "Secretary",
      "Pizza delivery guy",
      "Accountant",
      "Han som alltid pratar om aktier",
    ],
  },
  {
    name: "Casino",
    roles: [
      "Bartender",
      "Security guard",
      "Manager",
      "Kalle som spelar bort alla pengar",
      "Dealer",
      "Han som räknar kort och vinner hela tiden",
      "En random chines",
    ],
  },
  {
    name: "Embassy",
    roles: [
      "Security guard",
      "Secretary",
      "Ambassador",
      "Diplomat",
      "Ex military",
      "Refugee",
      "Tourist",
    ],
  },
  {
    name: "Hospital",
    roles: [
      "Nurse",
      "Doctor",
      "Trainee",
      "Therapist",
      "Surgeon",
      "Paulo Macarini (Googla)",
      "Patient",
      "Snubben som bokstavligt talat är död",
    ],
  },
  {
    name: "Hotel",
    roles: [
      "Bag boy",
      "Manager",
      "Security guard",
      "Cleaner",
      "Medelålders farsa som vill uppgradera sitt rum",
      "Customer",
      "Hunden som inte får komma in",
      "Receptionist",
    ],
  },
  {
    name: "Military base",
    roles: [
      "Officer",
      "Soldier",
      "Snubben som ångrar att han gick med i militären",
      "Weapon expert",
      "Fighter pilot",
      "Mechanic",
      "Doktor",
    ],
  },
  {
    name: "Film studio",
    roles: [
      "Director",
      "Stunt man",
      "Actor",
      "Camera man",
      "Producer",
      "Tonåring som blev anställd för att hämta kaffe",
      "Costume designer",
    ],
  },
  {
    name: "Västtrafik-tåg",
    roles: [
      "Train driver",
      "Passenger",
      "Biljett kontrollant-kärring",
      "Tonåring som gömer sig på toa för att inte köpa biljett",
      "Barnet som skriker hela resan",
      "Alibaban som säljer hash till sina polare",
      "Snubben som verkligen vill till jobbet",
    ],
  },
  {
    name: "Pirate ship",
    roles: [
      "Slave",
      "Captain",
      "Skrikig jävla papegoja",
      "Cannon operator",
      "Prisoner",
      "Snubben som går på plankan",
      "Chef",
      "Crew member",
    ],
  },
  {
    name: "Police station",
    roles: [
      "Detective",
      "Leif GW vid kaffemaskinen",
      "Journalist",
      "Criminal",
      "Tjock polis som äter donuts från skägget",
      "Lawyer",
      "Field police",
    ],
  },
  {
    name: "Restaurant",
    roles: [
      "Band mamber",
      "Piano player",
      "Food critic",
      "Chef",
      "Waitress",
      "Guest",
      "Barnet som beställer pankakor även om det inte finns på menyn",
    ],
  },
  {
    name: "School",
    roles: [
      "Principal",
      "Ronnie med matlådor",
      "Cleaner",
      "Teacher",
      "Elever som inte gör nånting",
      "2a som har sönder pingisrack",
      "Elvis som skjuter upp på deadlines",
    ],
  },
  {
    name: "Donken",
    roles: [
      "Raggarsvin",
      "Fyllo",
      "Underbetald personal",
      '"Kock"',
      "Stackarn som måste städa toan",
      "Alex som använder sina donkenpoäng",
      "Pontus som försöker att överleva ett nattskift",
    ],
  },
  {
    name: "TC-Stenungsund",
    roles: [
      "The matlådor-god Ronnie",
      "Nigglas",
      "Just Fors",
      "Hogia-Axel",
      "Traitor-Lext",
      "Dread-Jonas",
      "Bike-Elvis",
      "Rektorn",
    ],
  },
  {
    name: "22TE4I",
    roles: [
      "Pontus",
      "Kalle",
      "Alex",
      "Nicolas",
      "Lina",
      "William",
      "Anton",
    ]
  },
];