const locations = [
  //vill du bidra lägg in saker här:// template:
  // {
  //   name: "Plats",
  //   roles: [
  //     "yrke",
  //     "yrke",
  //   ],
  // },

  {
    name: "Flygplan",
    roles: [
      "Första klass passagerare",
      "Mekaniker",
      "Flygvärdinna",
      "Pilot",
      "Terrorist",
      "Passagerare",
      "Barnet som skriker under hela flygresan",
      "Andrepilot",
    ],
  },
  {
    name: "Bank",
    roles: [
      "Manager",
      "Konsult",
      "Bankrånare",
      "SecuritasVakt",
      "Bankbiträde",
      "Kund",
      "Hund kopplad till ett staket utanför",
    ],
  },
  {
    name: "Sandstrand",
    roles: [
      "Surfare",
      "Farsan med alldeles för mycket solkräm",
      "Strandvakt",
      "Snubben som flexar sina muskler lite för mycket",
      "Stekheta bruden som alla kollar på",
      "Glassförsäljare",
      "Barn som drunknar",
    ],
  },
  {
    name: "Kyrka",
    roles: [
      "Präst",
      "Syndare",
      "Gammal tant",
      "Snubbe som konfirmerar sig för pengarna",
      "Gubbe som spelar Orgel",
      "Turist",
    ],
  },
  {
    name: "Cirkus",
    roles: [
      "Akrobat",
      "Lejon tämjare",
      "Clown",
      "Eldslukare",
      "Barn som äter för mycket popcorn och dör",
      "Publik",
      "Kritiker",
    ],
  },
  {
    name: "Företagsfest",
    roles: [
      "Ceo",
      "Snubben som inte var inbjuden",
      "Strippan som var tänkt som underhållning",
      "Sekreterare",
      "Pizzabud",
      "Revisor",
      "Han som alltid pratar om aktier",
    ],
  },
  {
    name: "Kasino",
    roles: [
      "Bartender",
      "Säkerhetsvakt",
      "Manager",
      "Kalle som spelar bort alla pengar",
      "Dealer",
      "Han som räknar kort och vinner hela tiden",
      "En random chines",
    ],
  },
  {
    name: "Ambassad",
    roles: [
      "Säkerhetsvakt",
      "Sekreterare",
      "Ambassadör",
      "Diplomat",
      "Ex militär",
      "Flykting",
      "Turist",
    ],
  },
  {
    name: "Sjukhus",
    roles: [
      "Sjuksköterska",
      "Doktor",
      "Praktikant",
      "Terapeut",
      "Kirurg",
      "Paulo Macarini(Googla det om ni inte vet)",
      "Patient",
      "Snubben som bokstavligt talat är död",
    ],
  },
  {
    name: "Hotel",
    roles: [
      "Väskpojke",
      "Manager",
      "Säkeretsvakt",
      "Städerska",
      "Medelålders farsa som vill uppgradera sitt rum",
      "Kund",
      "Hunden som inte får komma in",
      "Receptionist",
    ],
  },
  {
    name: "Militärbas",
    roles: [
      "Officerare",
      "Soldat",
      "Snubben som ångrar att han gick med i militären",
      "Vapenexpert",
      "Stridspilot",
      "Mekaniker",
      "Läkare",
    ],
  },
  {
    name: "Film-Studio",
    roles: [
      "Regissör",
      "Stuntman",
      "Skådespelare",
      "Kameraman",
      "Producent",
      "Tonåring som blev anställd för att hämta kaffe",
      "Kostymdesigner",
    ],
  },
  {
    name: "Västtrafik tåg",
    roles: [
      "Lokförare",
      "Passagerare",
      "Biljett kontrollant",
      "Tonåring som gömer sig på toa för att inte köpa biljett",
      "Barnet som skriker hela resan",
      "Alibaban som säljer hash till sina polare",
      "Snubben som verkligen vill till jobbet",
    ],
  },
  {
    name: "Pirat skepp",
    roles: [
      "Slav",
      "Kapten",
      "Styrman",
      "Kanonoperatör",
      "Fånge",
      "Snubben som går på plankan",
      "Kock",
      "Besättningsmedlem",
    ],
  },
  {
    name: "Polisstation",
    roles: [
      "Detektiv",
      "Leif GW vid kaffemaskinen",
      "Journalist",
      "Kriminell",
      "Kriminalare",
      "Advokat",
      "Fältpolis",
    ],
  },
  {
    name: "Resturang",
    roles: [
      "Bandmedlem",
      "Värd",
      "Matkritiker",
      "Kock",
      "Servitris",
      "Kund",
      "Barnet som beställer pankakor även om det inte finns på menyn",
    ],
  },
  {
    name: "Skola",
    roles: [
      "Rektor",
      "Ronnie med matlådor",
      "städare",
      "Elever som inte gör nånting",
      "2a som har sönder pingisrack",
      "Elvis som skjuter upp på deadlines",
    ],
  },
  {
    name: "Donken",
    roles: [
      "Raggarsvin",
      "fyllo",
      "Underbetald personal",
      "Kock",
      "Stackarn som måste städa toan",
      "Alex som använder sina donkenpoäng",
      "Pontus som försöker att överleva ett nattskift",
    ],
  },
];
